name: test_coverage

on: [push]


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements_test.txt

      - name: build coverage file
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TEST_CHAT: ${{ secrets.TEST_CHAT }}
        run: |
          pytest --cache-clear --cov-fail-under=75 -v --cov=dff_telegram_connector tests > pytest-coverage.txt
